resolver:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/19/22.yaml

packages:
  - .

extra-deps:
  - git: https://github.com/llvm-hs/llvm-hs.git
    commit: d694c1a0d8941591dffb8c2f7877712e04ab3e7e
    subdirs:
      - llvm-hs
      - llvm-hs-pure

nix:
  pure: false
